### ISSUE TITLE
本地调试 Docker 部署该模板代码，运行报错：(node:31) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### ISSUE THREAD

**Issue by developer-zsg** [WeixinCloud/wxcloudrun-express#14]
> wxcloudrun-express@1.0.0 start /app
> node index.js

(node:31) UnhandledPromiseRejectionWarning: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at ConnectionManager.connect (/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:92:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ConnectionManager._connect (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:220:24)
    at async /app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /app/node_modules/sequelize/lib/sequelize.js:301:26
    at async MySQLQueryInterface.tableExists (/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:102:17)
    at async Function.sync (/app/node_modules/sequelize/lib/model.js:939:21)
    at async init (/app/db.js:25:3)
    at async bootstrap (/app/index.js:55:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by developer-zsg** [comment]
solved！
